/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Query");
gchar *s = N_("Placeholder text.");
gchar *s = N_("*");
gchar *s = N_("Message");
gchar *s = N_("Placeholder text.");
gchar *s = N_("User Information");
gchar *s = N_("Full Name:");
gchar *s = N_("Office:");
gchar *s = N_("Office Phone Number:");
gchar *s = N_("Home Phone Number:");
gchar *s = N_("Login Shell:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
