#!/bin/sh
prog=/usr/sbin/shutdown
for flag in $* ; do
	if test ${flag} = "-h" ; then
		prog=/usr/bin/halt
	elif test ${flag} = "-r" ; then
		prog=/usr/bin/reboot
	else
		args="$args $flag"
	fi
done
exec $prog $args
